# Generated by Django 5.2.5 on 2025-09-02 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('urgencia', models.CharField(choices=[('B', 'Baixa'), ('M', 'Moderada'), ('A', 'Alta')], max_length=1)),
                ('status', models.CharField(default='Aberto', max_length=50)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('filial_solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tickets.filial')),
            ],
        ),
    ]
