# Generated by Django 5.2.5 on 2025-09-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='numero_pc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
