# Generated by Django 5.2.5 on 2025-09-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_chamado_numero_pc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Em Atendimento', 'Em Atendimento'), ('Aguardando Informação', 'Aguardando Informação'), ('Resolvido', 'Resolvido'), ('Fechado', 'Fechado')], default='Aberto', max_length=50),
        ),
    ]
